[DEFAULT]
## Root directory for data files
datadir = ../../data/

## Host data file from primary distance indicators
host_data = host_data.dat

## Data file for calibrator and Hubble flow SNe Ia
sn1a_calib = sn1a_calib.dat
sn1a_hf = sn1a_hf_pp.dat
sn1a_hf_cov = sn1a_covar_pp.dat
sn1a_vp = 2m++  

## SBF data
sbf_calib = sbf_calib.dat
sbf_hf = sbf_hf.dat
sbf_v = 2m++

#Groups file (contains hosts for SBF)
groups=groups.dat

## Exclusion/inclusion lists for host data. Provide only one of them. Lists are comma spearated. Use "&" to exclude only if both are satisfied. You can specify host:, anchor:, or source:
host_exclude_list =  *jagb*, *mira*, b25, SMC

## Cosmological parameters
q0 = -0.55
j0 = 1

## Megamaser measurements
mm = megamaser.dat

## Velocity correction choices
vcorr_mm = 2M++

## Error parameters
vpec_error = 240.0
sbf_vpec_error= 240.0 

## Flags for warnings and outputs
; verbose = True
warn = False
