[meta]
base = base_variants_config.ini

[V00 - Baseline]

[V01 - Baseline + JAGB]
host_exclude_list =  *mira*, SMC, b25

[V02 - Baseline + Miras]
host_exclude_list =  *jagb*, SMC, b25

[V03 - Baseline + DESI FP calibrated to Coma]
coma = coma_sn.dat
sigma_mag_fp = 0.0371

[V04 - Baseline + empirically calibrated SNe II]
sn2_calib = sn2_calib.dat
sn2_hf = sn2_hf.dat

[V05 - Baseline + SNe II with Expanding Photosphere method]
epm = epm.dat         
vcorr_epm =2M++

[V06 - Baseline + Tully-Fisher]
tf_calib = tf_calib.dat
tf_hf = tf_hf.dat
tf_v = 2m++  

[V07 - Baseline + SMC]
host_exclude_list =  *jagb*, *mira*, b25

[V08 - Baseline without Cepheids]
host_exclude_list =  *jagb*, *mira*, *ceph*, SMC, b25

[V08B - Baseline with matching calibrators to V08 (custom baseline)]
calib_exclude = M1337, N0105, N0691, N0976, N1015, N2608, N3147, N3254, N3583, N4680, N5468, N5728, N5917, N7329, N7541, N7678, U9391

[V09 - Baseline without TRGB (SBF/groups automatically excluded)]
host_exclude_list =  *jagb*, *mira*, *trgb*, SMC, b25

[V09B - Baseline with matching calibrators to V09 (custom baseline)]
; calib_exclude = M66, M96, N1316, N1380, N1404, N4414, N4457, N4526, N4666, N7814, IC2006, N1344, N1374, N1375, N1380, N1399, N1404, N4458, N4472, N4489, N4552, N4636, N4649, N4697
calib_exclude = M66, M96, N1316, N1380, N1404, N4414, N4457, N4526, N4666, N7814

[V10 - Baseline without Gaia parallaxes, MW]
host_exclude_list =  *jagb*, *mira*, *MW*, SMC, b25

[V11 - Baseline without DEB, LMC, SMC]
host_exclude_list =  *jagb*, *mira*, *LMC*, SMC, b25

[V12 - Baseline without NGC 4258 (SBF/groups automatically excluded)]
host_exclude_list =  *jagb*, *mira*, *N4258*, SMC, b25

[V12B - Baseline with matching calibrators to V12 (custom baseline)]
calib_exclude = M66, M96, N1316, N1380, N1404, N4414, N4457, N4526, N4666, N7814, IC2006, N1344, N1374, N1375, N1380, N1399, N1404, N4458, N4472, N4489, N4552, N4636, N4649, N4697
; calib_exclude = M66, M96, N1316, N1380, N1404, N4414, N4457, N4526, N4666, N7814

[V13 - Baseline without SNe Ia]
sn1a_calib =
sn1a_hf =
sn1a_hf_cov =
sn1a_vp =

[V14 - Baseline without SBF]
sbf_calib = 
sbf_hf = 
sbf_v = 

groups = 

[V15 - Baseline without masers in the Hubble flow]
mm=

[V16 - Exclude HST data, LMC, MW]
host_exclude_list =  *jagb*, *mira*, MW, *hst*, LMC, SMC, b25

[V16B - Baseline with matching calibrators to V16 (custom baseline)]
calib_exclude = M1337, M66, M96, N0105, N0691, N0976, N1015, N1309, N1316, N2608, N3021, N3147, N3254, N3583, N3982, N4414, N4457, N4526, N4666, N4680, N5728, N5917, N7329, N7541, N7678, N7814, U9391

[V17 - Exclude JWST data (SBF/groups automatically excluded)]
host_exclude_list =  *jagb*, *mira*, *jwst*, SMC, b25

[V18 - Exclude SN 1994D and earlier]
calib_exclude = 198*, *1990*, *1991*, *1992*, *1993*, *1994D*

[V19 - Baseline with SNe Ia, SBF, Masers in CMB frame]
sn1a_vp = cmb
sbf_v = cmb
vcorr_mm = GROUP

[V20 - SNe Ia in redshift range 0.023--0.06 without SBF]
zmin_hf=0.023
zmax_hf=0.06
z_range_sn1a= True

sbf_calib = 
sbf_hf = 
sbf_v = 

groups = 

[V21 - SNe Ia in redshift range 0.03--0.10 without SBF]
zmin_hf=0.03
zmax_hf=0.1
z_range_sn1a = True

sbf_calib = 
sbf_hf = 
sbf_v = 

groups = 

[V22 - SNe Ia from CSP, all 55 calibrators]
sn1a_calib = sn1a_cal_csp_burns.dat
sn1a_hf = hf_csp_lluis_v2.dat
sn1a_hf_cov = hf_csp_lluis_v2_cov.dat
sn1a_vp = 2m++  

[V23 - SNe Ia from BayesSN]
sn1a_calib = sn1a_calib_bayessn.dat
sn1a_intrinsic = 0.15
sn1a_hf = sn1a_hf_bayessn.dat
sn1a_hf_cov = sn1a_covar_bayessn.dat
sn1a_vp = 2m++  

[V24 - SNe Ia from SALT3 filtered PP]
sn1a_calib = rung3_salt3.dat
sn1a_hf = hf_salt3.dat
sn1a_hf_cov = hf_salt3_cov.dat
sn1a_vp = 2m++

[V25 - SNe Ia in H-band]
sn1a_IR = TRUE
sn1a_calib = sn1a_calib_H.dat
sn1a_intrinsic = 0.096 
sn1a_hf = sn1a_hf_H.dat
sn1a_hf_cov = 
sn1a_vp = 2m++

[V26 - SNe Ia in J-band]
sn1a_IR = TRUE
sn1a_calib = sn1a_calib_J.dat
sn1a_intrinsic = 0.125
sn1a_hf = sn1a_hf_J.dat
sn1a_hf_cov = 
sn1a_vp = 2m++

[V27 - Ignore off-diagonal covariance for SNe Ia in Hubble flow]
sn1a_ignore_offdiag = True

[V28 - No metallicity correction for Cepheid PL]
host_data = host_data_nomet.dat

[V97 - All SNe Ia and nothing else]
host_exclude_list = SMC, b25

mm = 

sbf_calib = 
sbf_hf = 
sbf_v = 

groups = 

[V98a - All except Sne Ia in Hubble flow and Coma]
host_exclude_list= b25

sn1a_calib =
sn1a_hf =
sn1a_hf_cov =
sn1a_vp =
unused_hosts_via_covariance = True

tf_calib = tf_calib.dat
tf_hf = tf_hf.dat
tf_v = 2m++  

sn2_calib = sn2_calib.dat
sn2_hf = sn2_hf.dat

epm = epm.dat         
vcorr_epm =2M++

[V98b - All except Sne Ia and TF in Hubble flow and Coma]
host_exclude_list= b25

sn1a_calib =
sn1a_hf =
sn1a_hf_cov =
sn1a_vp =
unused_hosts_via_covariance = True

sn2_calib = sn2_calib.dat
sn2_hf = sn2_hf.dat

epm = epm.dat         
vcorr_epm =2M++

[V98c - Only TF in Hubble flow]
host_exclude_list= b25

sn1a_calib =
sn1a_hf =
sn1a_hf_cov =
sn1a_vp =
unused_hosts_via_covariance = True

tf_calib = tf_calib.dat
tf_hf = tf_hf.dat
tf_v = 2m++  

sbf_calib = 
sbf_hf = 
sbf_v = 

mm =

groups = 

[V99 - Everything available]
host_exclude_list= b25

sn2_calib = sn2_calib.dat
sn2_hf = sn2_hf.dat

tf_calib = tf_calib.dat
tf_hf = tf_hf.dat
tf_v = 2m++  

coma = coma_sn.dat
sigma_mag_fp = 0.0371

epm = epm.dat         
vcorr_epm =2M++

[V99a - Everything available except TF]
host_exclude_list= b25

sn2_calib = sn2_calib.dat
sn2_hf = sn2_hf.dat

coma = coma_sn.dat
sigma_mag_fp = 0.0371

epm = epm.dat         
vcorr_epm =2M++

[O1 - MW+LMC+SMC+Ceph+SNIa+FP]
host_exclude_list = N4258

coma = coma_sn.dat
sigma_mag_fp = 0.0371

mm = 

sbf_calib = 
sbf_hf = 
sbf_v = 

groups = 

[O2 - N4258+TRGB+SBF+Megamaser]
host_exclude_list = 
host_include_list = *trgb*

sn1a_calib =
sn1a_hf =
sn1a_hf_cov =
sn1a_vp =

[O2_V99a - N4258+TRGB+SBF+Megamaser+SNII+EPM]
; host_exclude_list = 
; host_include_list = *trgb*
host_exclude_list = LMC, MW, SMC, b25

sn1a_calib =
sn1a_hf =
sn1a_hf_cov =
sn1a_vp =

sn2_calib = sn2_calib.dat
sn2_hf = sn2_hf.dat

epm = epm.dat         
vcorr_epm =2M++

[O2_V99 - N4258+TRGB+SBF+Megamaser+SNII+EPM+TF]
; host_exclude_list = 
; host_include_list = *trgb*
host_exclude_list = LMC, MW, SMC, b25

sn1a_calib =
sn1a_hf =
sn1a_hf_cov =
sn1a_vp =

sn2_calib = sn2_calib.dat
sn2_hf = sn2_hf.dat

tf_calib = tf_calib.dat
tf_hf = tf_hf.dat
tf_v = 2m++  

epm = epm.dat         
vcorr_epm =2M++